from setuptools import setup, find_packages

setup(
    name="code-understanding-rag",
    version="0.1.0",
    description="RAG system for code understanding and analysis",
    author="Your Name",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "fastapi",
        "uvicorn",
        "pydantic",
        "langchain",
        "langchain-openai",
        "langchain-anthropic",
        "openai",
        "anthropic",
        "chromadb",
        "faiss-cpu",
        "sentence-transformers",
        "tiktoken",
        "sqlalchemy",
        "python-dotenv",
        "python-multipart",
        "pydot",
        "networkx",
        "matplotlib",
        "pandas",
        "numpy",
        "pytest",
        "httpx",
        "loguru",
    ],
)
